include_guard(GLOBAL)
include("${CMAKE_CURRENT_LIST_DIR}/CPM.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/DependencyPins.cmake")
find_package(Threads REQUIRED)
# Runtime consumes Pub delivery and Pipeline boundary ordering even without tests.
CPMAddPackage(NAME Sub0Pipeline GITHUB_REPOSITORY CraigHutchinson/Sub0Pipeline
    GIT_TAG ${CRUCIBLE_SUB0PIPELINE_REVISION} EXCLUDE_FROM_ALL YES
    OPTIONS "SUB0PIPELINE_BUILD_TESTING OFF" "SUB0PIPELINE_BUILD_EXAMPLES OFF"
    "SUB0PIPELINE_BUILD_BENCHMARKS OFF" "SUB0PIPELINE_PLATFORM_DESKTOP OFF"
    "SUB0PIPELINE_PLATFORM_PRIORITY OFF")
CPMAddPackage(NAME Sub0Pub GITHUB_REPOSITORY CraigHutchinson/Sub0Pub
    GIT_TAG ${CRUCIBLE_SUB0PUB_REVISION} EXCLUDE_FROM_ALL YES
    OPTIONS "SUB0PUB_BUILD_TESTING OFF" "SUB0PUB_BUILD_EXAMPLES OFF")
if(BUILD_TESTING OR CRUCIBLE_ENABLE_DIAGNOSTICS)
    # Diagnostics are optional; a production build without them does not fetch Log.
    CPMAddPackage(NAME Sub0Log GITHUB_REPOSITORY CraigHutchinson/Sub0Log
        GIT_TAG ${CRUCIBLE_SUB0LOG_REVISION} EXCLUDE_FROM_ALL YES
        OPTIONS "SUB0LOG_BUILD_TESTING OFF" "SUB0LOG_BUILD_EXAMPLES OFF"
        "SUB0LOG_BUILD_BENCHMARKS OFF" "SUB0LOG_BUILD_TOOLS OFF" "SUB0LOG_INSTALL OFF")
endif()

CPMAddPackage(NAME Sub0ECS GITHUB_REPOSITORY CraigHutchinson/Sub0ECS
    GIT_TAG ${CRUCIBLE_SUB0ECS_REVISION} EXCLUDE_FROM_ALL YES
    OPTIONS "SUB0ECS_BUILD_TESTING OFF" "SUB0ECS_BUILD_BENCHMARKS OFF")

CPMAddPackage(NAME Sub0HexGrid GITHUB_REPOSITORY CraigHutchinson/Sub0HexGrid
    GIT_TAG ${CRUCIBLE_SUB0HEXGRID_REVISION} EXCLUDE_FROM_ALL YES
    OPTIONS "SUB0HEXGRID_BUILD_TESTS OFF" "SUB0HEXGRID_BUILD_EXAMPLES OFF"
    "SUB0HEXGRID_BUILD_BENCHMARKS OFF"
    "SUB0HEXGRID_ENABLE_SANITIZERS ${CRUCIBLE_ENABLE_SANITIZERS}")
