include_guard(GLOBAL)
# Optional desktop and GPU adapters consume SDL. Ordinary headless builds do not fetch it.
CPMAddPackage(NAME SDL3 GITHUB_REPOSITORY libsdl-org/SDL
    GIT_TAG ${CRUCIBLE_SDL_REVISION} EXCLUDE_FROM_ALL YES
    OPTIONS "SDL_STATIC ON" "SDL_SHARED OFF" "SDL_TESTS OFF" "SDL_TEST_LIBRARY OFF"
    "SDL_EXAMPLES OFF" "SDL_INSTALL OFF" "SDL_UNINSTALL OFF" "SDL_LIBC ON"
    "SDL_AUDIO OFF" "SDL_HAPTIC OFF" "SDL_JOYSTICK OFF" "SDL_SENSOR OFF"
    "SDL_CAMERA OFF" "SDL_DIALOG OFF" "SDL_TRAY OFF"
    "SDL_ASAN ${CRUCIBLE_ENABLE_SANITIZERS}")
